spring.application.name=latex-editor

spring.datasource.url=jdbc:sqlite:latex-editor.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# MinIO Configuration
minio.url=http://localhost:9000
minio.access.key=admin
minio.secret.key=StrongPassword123
minio.bucket.name=latex-project-files
minio.auto.create.bucket=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.allowed-types=application/pdf,image/png,image/jpeg,text/plain,application/zip,application/x-tex,text/x-tex